# Python de cero a experto
**Autor:** Luis Miguel de la Cruz Salas

<a href="https://github.com/luiggix/Python_cero_a_experto">Python de cero a experto</a> by Luis M. de la Cruz Salas is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0?ref=chooser-v1">Attribution-NonCommercial-NoDerivatives 4.0 International</a>


**Objetivos.**
...

## Numpy

Inicialmente conocido como **Numeric**, fue desarrollado en 1995, principalmente por *Jim Hugunin*. 
Es la biblioteca fundamental para hacer cómputo científico.

Para usar todas las herramientas de numpy debemos importar la biblioteca como sigue:

In [1]:
import numpy as np

### Creación de arreglos simples
`np.array`
`np.arange`
`np.linspace`
`np.zeros`
`np.ones`

In [35]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (10,) 
 size : 8


In [37]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x = np.arange(1,11,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (10,) 
 size : 8


In [40]:
x = np.linspace(1,10,10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size : 8


In [43]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size : 8


In [45]:
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size : 8


In [47]:
x *= 45
x

array([45., 45., 45., 45., 45., 45., 45., 45., 45., 45.])

In [48]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size : 8


In [50]:
# Modificar el tipo de dato de los elementos del arreglo
# La modificación afecta al arreglo 'y' pero no al arreglo 'x' (no es inplace)
y = x.astype(int)

In [51]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size : 8


In [98]:
print(f' tipo  : {type(y)} \n dtype : {y.dtype} \n dim   : {y.ndim} \n shape : {y.shape} \n size : {y.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 2 
 shape : (6, 4) 
 size : 8


In [53]:
print(id(x), id(y))

139979675525808 139979675527008


### Arreglos multidimensionales

In [54]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [55]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : complex128 
 dim   : 2 
 shape : (3, 2) 
 size : 16


In [61]:
x = np.array( [ [1,2], [3,4] ], dtype=complex )
x

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [62]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : complex128 
 dim   : 2 
 shape : (2, 2) 
 size : 16


In [66]:
x = np.array( [ [[1,2], [3,4]], [[5,6], [7,8]] ])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [67]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 2, 2) 
 size : 8


In [80]:
x = np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [81]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 2 
 shape : (10, 10) 
 size : 8


In [74]:
x = np.ones((4,3,2))
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [75]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 3 
 shape : (4, 3, 2) 
 size : 8


In [90]:
x = np.empty((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [91]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 3 
 shape : (2, 3, 4) 
 size : 8


### Cambiando el `shape` de los arreglos
#### Función `reshape`

In [120]:
x = np.array([ [[ 1, 2, 3, 4],
                [ 5, 6, 7, 8],
                [ 9,10,11,12]],
               [[13,14,15,16],
                [17,16,19,20],
                [21,22,23,24]] ])
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')
print(f'x = \n {x}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size : 8
x = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]]


In [121]:
y = x.reshape(6,4)
print(f' tipo  : {type(y)} \n dtype : {y.dtype} \n dim   : {y.ndim} \n shape : {y.shape} \n size : {y.itemsize}')
print(f'y = \n {y}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 2 
 shape : (6, 4) 
 size : 8
y = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 16 19 20]
 [21 22 23 24]]


In [122]:
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')
print(f'x = \n {x} \n')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size : 8
x = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]] 



In [124]:
y = x.reshape(24)
print(f' tipo  : {type(y)} \n dtype : {y.dtype} \n dim   : {y.ndim} \n shape : {y.shape} \n size : {y.itemsize}')
print(f'y = \n {y}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (24,) 
 size : 8
y = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 16 19 20 21 22 23 24]


In [131]:
y = x.reshape(2,3,4)
print(f' tipo  : {type(y)} \n dtype : {y.dtype} \n dim   : {y.ndim} \n shape : {y.shape} \n size : {y.itemsize}')
print(f'y = \n {y}')
print(f'x = \n {x}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size : 8
y = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]]
x = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]]


#### Atributo `shape` (inplace)

In [133]:
y.shape

(2, 3, 4)

In [134]:
y.shape = (6,4)
y.shape

(6, 4)

In [135]:
print(f' tipo  : {type(y)} \n dtype : {y.dtype} \n dim   : {y.ndim} \n shape : {y.shape} \n size : {y.itemsize}')
print(f'y = \n {y}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 2 
 shape : (6, 4) 
 size : 8
y = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 16 19 20]
 [21 22 23 24]]


#### Creando un arreglo y modificando su `shape` al vuelo

In [136]:
x = np.arange(24).reshape(2,3,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [139]:
x = np.arange(1,25,1).reshape(2,3,4)
print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size : {x.itemsize}')
x

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size : 8


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### Operaciones básicas entre arreglos

In [141]:
v1 = np.array([2.3,3.1,9.6])
v2 = np.array([3.4,5.6,7.8])

In [142]:
(1/3)*v1 # Escalar por arreglo

array([0.76666667, 1.03333333, 3.2       ])

In [143]:
v1+v2 # Suma de arreglos

array([ 5.7,  8.7, 17.4])

In [144]:
v1-v2 # Resta de arreglos

array([-1.1, -2.5,  1.8])

In [145]:
v1*v2 # Multiplicación elemento a elemento

array([ 7.82, 17.36, 74.88])

In [146]:
v1/v2 # División elemento a elemento

array([0.67647059, 0.55357143, 1.23076923])

In [147]:
v1 ** 2 # Potencia de un arreglo

array([ 5.29,  9.61, 92.16])

In [148]:
v1 % 2  # Modulo de un arreglo

array([0.3, 1.1, 1.6])

In [151]:
10 * np.sin(v1) # Aplicación de una función matemática a cada elemento del arreglo

array([ 7.45705212,  0.41580662, -1.74326781])

In [154]:
v1 > 3 # Operación de comparación, devuelve un arreglo Booleano

array([False,  True,  True])