# Python de cero a experto
**Autor:** Luis Miguel de la Cruz Salas

<a href="https://github.com/luiggix/Python_cero_a_experto">Python de cero a experto</a> by Luis M. de la Cruz Salas is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/4.0?ref=chooser-v1">Attribution-NonCommercial-NoDerivatives 4.0 International</a>

## Numpy

Es una biblioteca de Python que permite crear y gestionar arreglos multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel que operan sobre estos arreglos. El sitio oficial es https://numpy.org/

Para usar todas las herramientas de numpy debemos importar la biblioteca como sigue:

In [1]:
import numpy as np
np.version.version

'1.19.2'

In [2]:
# Función para obtener los atributos de arreglos
info_array = lambda x: print(f' tipo  : {type(x)} \n dtype : {x.dtype} \n dim   : {x.ndim} \n shape : {x.shape} \n size(bytes) : {x.itemsize} \n size(elements) : {x.size}')

### Creación de arreglos simples

#### Ejemplo 1.
Crear un arreglo de números del 1 al 10 usando:
`np.array`, `np.arange`, `np.linspace`, `np.zeros`, `np.ones`, `np.random.rand`

In [3]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [5]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
x = np.arange(1,11,1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


**Ojo** `np.arange()` acepta parámetros flotantes:

In [10]:
xf = np.arange(1, 11, 1.0)
xf

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [11]:
info_array(xf)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [12]:
xf = np.arange(0.3, 0.7, 0.12)
xf

array([0.3 , 0.42, 0.54, 0.66])

In [15]:
x = np.linspace(1,10,10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


**Ojo**: con `np.linspace` es posible generar un número exacto de elementos, por ejemplo:

In [18]:
xf = np.linspace(0.3, 0.7, 6)
xf

array([0.3 , 0.38, 0.46, 0.54, 0.62, 0.7 ])

In [19]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
for i,val in enumerate(x):
    x[i] = i+1 
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [22]:
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [24]:
for i,val in enumerate(x):
    x[i] = i+val 
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
x *= 2
x

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [26]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [27]:
x = np.random.rand(10)
info_array(x)
x

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


array([0.66433246, 0.58444186, 0.30326977, 0.1347962 , 0.03618753,
       0.88728637, 0.3863712 , 0.73929291, 0.77945595, 0.89361614])

In [28]:
x = np.random.rand(2,5)
info_array(x)
x

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 2 
 shape : (2, 5) 
 size(bytes) : 8 
 size(elements) : 10


array([[0.72607276, 0.10507615, 0.53244085, 0.76941555, 0.77880996],
       [0.28101446, 0.79369621, 0.12481409, 0.06639868, 0.11730008]])

### Modificar el tipo de dato de los elementos del arreglo

In [29]:
x = np.linspace(1,10,10)
# La modificación afecta al arreglo 'y' pero no al arreglo 'x' (no es inplace)
y = x.astype(int)

In [30]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [31]:
info_array(y)

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (10,) 
 size(bytes) : 8 
 size(elements) : 10


In [32]:
print(id(x), id(y))

140596824092304 140596824092224


In [33]:
print(x)
print(y)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1  2  3  4  5  6  7  8  9 10]


### Arreglos multidimensionales

In [34]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [35]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : complex128 
 dim   : 2 
 shape : (3, 2) 
 size(bytes) : 16 
 size(elements) : 6


In [36]:
x = np.array( [ [1,2], [3,4] ], dtype=complex )
x

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [37]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : complex128 
 dim   : 2 
 shape : (2, 2) 
 size(bytes) : 16 
 size(elements) : 4


In [39]:
x = np.array( [ [[1,2], [3,4]], [[5,6], [7,8]] ])
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 2, 2) 
 size(bytes) : 8 
 size(elements) : 8


In [41]:
x = np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [42]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 2 
 shape : (10, 10) 
 size(bytes) : 8 
 size(elements) : 100


In [43]:
x = np.ones((4,3,2))
x

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [44]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 3 
 shape : (4, 3, 2) 
 size(bytes) : 8 
 size(elements) : 24


In [45]:
x = np.empty((2,3,4))
x

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [46]:
info_array(x)

 tipo  : <class 'numpy.ndarray'> 
 dtype : float64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24


### Cambiando el `shape` de los arreglos
#### Función `reshape`

In [47]:
x = np.array([ [[ 1, 2, 3, 4],
                [ 5, 6, 7, 8],
                [ 9,10,11,12]],
               [[13,14,15,16],
                [17,16,19,20],
                [21,22,23,24]] ])
info_array(x)
print(f'x = \n {x}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24
x = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]]


In [50]:
y = x.reshape(6,4)
info_array(y)
print(f'y = \n {y}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 2 
 shape : (6, 4) 
 size(bytes) : 8 
 size(elements) : 24
y = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 16 19 20]
 [21 22 23 24]]


In [51]:
info_array(x)
print(f'x = \n {x} \n')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24
x = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]] 



In [52]:
y = x.reshape(24)
info_array(y)
print(f'y = \n {y}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 1 
 shape : (24,) 
 size(bytes) : 8 
 size(elements) : 24
y = 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 16 19 20 21 22 23 24]


In [53]:
y = x.reshape(2,3,4)
info_array(y)
print(f'y = \n {y}')
print(f'x = \n {x}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24
y = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]]
x = 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 16 19 20]
  [21 22 23 24]]]


In [55]:
# Otra manera
np.reshape(x, (6,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 16, 19, 20],
       [21, 22, 23, 24]])

In [56]:
x

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 16, 19, 20],
        [21, 22, 23, 24]]])

#### Atributo `shape` (inplace)

In [57]:
y.shape

(2, 3, 4)

In [58]:
y.shape = (6,4)
y.shape

(6, 4)

In [59]:
info_array(y)
print(f'y = \n {y}')

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 2 
 shape : (6, 4) 
 size(bytes) : 8 
 size(elements) : 24
y = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 16 19 20]
 [21 22 23 24]]


#### Creando un arreglo y modificando su `shape` al vuelo

In [60]:
x = np.arange(24).reshape(2,3,4)
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [61]:
x = np.arange(1,25,1).reshape(2,3,4)
info_array(x)
x

 tipo  : <class 'numpy.ndarray'> 
 dtype : int64 
 dim   : 3 
 shape : (2, 3, 4) 
 size(bytes) : 8 
 size(elements) : 24


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

### Copias y vistas de arreglos

In [73]:
x = np.array([1,2,3,4])
z = x  # z es un sinónimo de x, no se crea una copia!
print(id(z), id(x))
print(z is x)
print(x is z)

140596828296656 140596828296656
True
True


**Los objetos que son *mutables* se pasan por referencia a una función:**

In [74]:
def f(a):
    print(id(a))

print(id(x))
print(f(x))

140596828296656
140596828296656
None


#### Copia superficial o vista de un arreglo

In [75]:
z = x.view()
print(id(z), id(x))
print(z is x)
print(x is z)
print(z.base is x) # Comparten la memoria 
print(z.flags.owndata) # Propiedades de la memoria
print(x.flags.owndata) # Propiedades de la memoria

140596828054352 140596828296656
False
False
True
False
True


In [76]:
print(z.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [77]:
z.shape =(2,2)
print(z.shape, z, sep = '\n')
print(x.shape, x, sep = '\n')

(2, 2)
[[1 2]
 [3 4]]
(4,)
[1 2 3 4]


In [78]:
z[1,1] = 1000
print(z.shape, z, sep = '\n')
print(x.shape, x, sep = '\n')

(2, 2)
[[   1    2]
 [   3 1000]]
(4,)
[   1    2    3 1000]


#### Copia completa de arreglos

In [79]:
z = x.copy()
print(id(z), id(x))
print(z is x)
print(x is z)
print(z.base is x) # Comparten la memoria 
print(z.flags.owndata) # Propiedades de la memoria
print(x.flags.owndata) # Propiedades de la memoria

140596827171776 140596828296656
False
False
False
True
True


In [80]:
print('z = ', z)
print('x = ', x)

z =  [   1    2    3 1000]
x =  [   1    2    3 1000]


In [81]:
z[3] = 4
print('z = ', z)
print('x = ', x)

z =  [1 2 3 4]
x =  [   1    2    3 1000]


#### Las rebanadas son vistas de arreglos
Las vistas de arreglos pueden ser útiles en ciertos casos, por ejemplo si tenemos un arreglo muy grande y solo deseamos mantener unos cuantos elementos del mismo, debemos hacer lo siguiente:

In [82]:
a = np.arange(int(1e5)) # Arreglo de 100000 elementos
b = a[:200].copy()      # Copia completa de 200 elementos de 'a'
del a                   # Eliminar la memoria que usa 'a'
b

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

**Pero si usamos rebanadas, el comportamiento es distinto**:

In [83]:
a = np.arange(int(1e5)) # Arreglo de 100000 elementos
b = a[:200]             # Vista de 200 elementos de 'a'
b[0] = 1000
print('b = ', b)
print('a = ', a)

b =  [1000    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189  190  191  192  193  194  195
 

### Rebanadas (slicing)

In [62]:
x = np.arange(0,10,1.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [63]:
x[:] # El arreglo completo

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
x[3:6] # Una sección del arreglo, de 3 a 5

array([3., 4., 5.])

In [65]:
x[2:9:2] # de 2 a 8, dando saltos de 2 en 2

array([2., 4., 6., 8.])

In [66]:
x[1:7:2] = 100 # modificando algunos elementos del arreglo
x

array([  0., 100.,   2., 100.,   4., 100.,   6.,   7.,   8.,   9.])

In [67]:
y = np.arange(36).reshape(6,6)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [68]:
y[1:4,:] # renglones de 1 a 3

array([[ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [69]:
y[:,1:5] # columnas de 1 a 4

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22],
       [25, 26, 27, 28],
       [31, 32, 33, 34]])

In [70]:
y[2:4,2:5] # seccion del arreglo

array([[14, 15, 16],
       [20, 21, 22]])

In [71]:
y[1:5:2,1:5:2] # sección del arreglo con saltos distintos de 1

array([[ 7,  9],
       [19, 21]])

In [72]:
y[1:5:2,1:5:2] = 0
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  0,  8,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18,  0, 20,  0, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

También es posible seleccionar elementos que cumplan cierto criterio.

In [ ]:
y[y<25] # Selecciona los elementos del arreglo que son menores que 25

In [ ]:
y[y%2==0] # Selecciona todos los elementos pares

In [ ]:
y[(y>8) & (y<20)] # Selecciona todos los elementos mayores que 8 y menores que 20

In [ ]:
y[(y>8) & (y<20)] = 666
y

In [ ]:
z = np.nonzero(y == 666) # Determina los renglones y las columnas donde se cumple la condición.
z

In [ ]:
indices = list(zip(z[0], z[1])) # Genera una lista de coordenadas donde se cumple la condición.
indices

In [ ]:
print(y[z]) # Imprime los elementos del arreglo 'y' usando las coordenadas de 'z'

### Operaciones básicas entre arreglos

In [ ]:
v1 = np.array([2.3,3.1,9.6])
v2 = np.array([3.4,5.6,7.8])

In [ ]:
(1/3)*v1 # Escalar por arreglo

In [ ]:
v1+v2 # Suma de arreglos

In [ ]:
v1-v2 # Resta de arreglos

In [ ]:
v1*v2 # Multiplicación elemento a elemento

In [ ]:
v1/v2 # División elemento a elemento

In [ ]:
v1 ** 2 # Potencia de un arreglo

In [ ]:
v1 % 2  # Modulo de un arreglo

In [ ]:
10 * np.sin(v1) # Aplicación de una función matemática a cada elemento del arreglo

In [ ]:
v1 > 3 # Operación de comparación, devuelve un arreglo Booleano

### Operaciones entre arreglos Booleanos

In [ ]:
f = np.array([True, False, False, True])
r = np.array([False, True, False, True])

In [ ]:
f & r

In [ ]:
f | r

In [ ]:
~f

In [ ]:
b = np.arange(4)
b

In [ ]:
b[f]

In [ ]:
b[f] = 100
b

### Métodos de los arreglos
Existe una larga lista de métodos definidas para los arreglos, vea más información <a href="https://numpy.org/doc/stable/reference/arrays.ndarray.html#array-ndarray-methods">aquí</a>.

In [ ]:
x = np.random.random(100) # arreglo de 100 números aleatorios entre 1 y 0
x

In [ ]:
x.max()

In [ ]:
x.sum()

In [ ]:
x = np.arange(10).reshape(2,5)
x

In [ ]:
x.T

In [ ]:
x.transpose()

In [ ]:
np.transpose(x)

In [ ]:
np.flip(x) # Cambiar el orden de los elementos del arreglo

In [ ]:
np.flip(x, axis=0)

In [ ]:
f1 = x.flatten() # Aplanar un arreglo
f1[0] = 1000
print(x)
print(f1)

In [ ]:
f2 = x.ravel() # Aplanar un arreglo
f2[0] = 1000
print(x)
print(f1)

**Los arreglos deben ser compatibles para poder realizar las operaciones anteriores:**

In [ ]:
a = np.arange(24).reshape(2,3,4)
b = np.arange(24).reshape(2,3,4)
a + b

In [ ]:
c = np.arange(24).reshape(6,4)
a + c

### Apilación y concatenación de arreglos

In [ ]:
a = np.arange(4).reshape(2,2)
b = np.arange(4,8,1).reshape(2,2)
print(a)
print(b)

In [ ]:
np.vstack( (a, b) ) # Apilación vertical 

In [ ]:
np.hstack( (a, b) ) # Apilación horizontal 

In [ ]:
x = np.arange(1,25,1).reshape(6,4)
x

In [ ]:
np.hsplit(x, 2) # División vertical en dos arreglos

In [ ]:
np.vsplit(x, 2) #  División horizontal en dos arreglos

**Se recomienda revisar la función <a href="https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate">`np.concatenate` </a> para ver más opciones**

### Agregando dimensiones al arreglo

In [ ]:
x = np.arange(1,11,1.)
info_array(x)
x

In [ ]:
x_row = x[np.newaxis, :]
info_array(x_row)
x_row

In [ ]:
x_col = x[:, np.newaxis]
info_array(x_col)
x_col

In [ ]:
# Otra manera
x_row = np.expand_dims(x, axis=0)
x_col = np.expand_dims(x, axis=1)
print(x_row)
print(x_col)

### Constantes

In [ ]:
np.e

In [ ]:
np.euler_gamma # Euler–Mascheroni constant

In [ ]:
np.pi

In [ ]:
np.inf # Infinito

In [ ]:
#Por ejemplo
np.array([1]) / 0.

In [ ]:
np.nan # Not a Number: Valor no definido o no representable

In [ ]:
# Por ejemplo
np.sqrt(-1)

In [ ]:
np.log([-1, 1, 2])

In [ ]:
np.NINF  # Infinito negativo

In [ ]:
# Por ejemplo
np.array([-1]) / 0.

In [ ]:
np.NZERO # Cero negativo

In [ ]:
np.PZERO # Cero positivo

### Exportando e importando arreglos a archivos

In [ ]:
x = np.arange(1,25,1.0).reshape(6,4)
print(x)
np.savetxt('arreglo.csv', x, fmt='%.2f', delimiter=',', header='1,  2,  3,  4')

In [ ]:
#Usando la biblioteca Pandas
import pandas as pd
df = pd.DataFrame(x)
df

In [ ]:
df.to_csv('arreglo_PD.csv')

In [ ]:
y = pd.read_csv('arreglo_PD.csv')
y